// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMDVPEr29Fh_lQp-92dX7P5UYAuTXyfQ',
    appId: '1:914072224342:web:b86ec950778844bff971f7',
    messagingSenderId: '914072224342',
    projectId: 'dalel-57947',
    authDomain: 'dalel-57947.firebaseapp.com',
    storageBucket: 'dalel-57947.appspot.com',
    measurementId: 'G-ZSSHBDFYND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RDwyXWAElqWX00GybEzOCeOW9popRzE',
    appId: '1:914072224342:android:1231229e78e749b0f971f7',
    messagingSenderId: '914072224342',
    projectId: 'dalel-57947',
    storageBucket: 'dalel-57947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxQlEWNakp-W9UaoQR7hFoeqKXGaNumw',
    appId: '1:914072224342:ios:dedcfbb26ae0a0fdf971f7',
    messagingSenderId: '914072224342',
    projectId: 'dalel-57947',
    storageBucket: 'dalel-57947.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxQlEWNakp-W9UaoQR7hFoeqKXGaNumw',
    appId: '1:914072224342:ios:dedcfbb26ae0a0fdf971f7',
    messagingSenderId: '914072224342',
    projectId: 'dalel-57947',
    storageBucket: 'dalel-57947.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMDVPEr29Fh_lQp-92dX7P5UYAuTXyfQ',
    appId: '1:914072224342:web:0602a913d6d4687af971f7',
    messagingSenderId: '914072224342',
    projectId: 'dalel-57947',
    authDomain: 'dalel-57947.firebaseapp.com',
    storageBucket: 'dalel-57947.appspot.com',
    measurementId: 'G-785B23C3DM',
  );
}
